---
title: "Homework 2"
author: "Calvin Wong"
date: "9/8/2018"
output:
  pdf_document: default
  html_document: default
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

2.6 Dice rolls. If you roll a pair of fair dice, what is the probability of
(a) getting a sum of 1?
Getting a sum of 1 with a pair of dice is impossible, therefore, the probability is 0.
(b) getting a sum of 5?
There are 4 combinations; (1,4), (2,3), (3,2), (4,1). Since the total combinations is 36. The probability of getting a sum of 5 is 4/36 = 0.111
(c) getting a sum of 12?
There is 1 combination; (6,6). Since the total combinations is 36. The probability of getting a sum of 12 is 1/36 = 0.027

2.8 Poverty and language. The American Community Survey is an ongoing survey that
provides data every year to give communities the current information they need to plan investments
and services. The 2010 American Community Survey estimates that 14.6% of Americans live below
the poverty line, 20.7% speak a language other than English (foreign language) at home, and 4.2%
fall into both categories.
(a) Are living below the poverty line and speaking a foreign language at home disjoint?
No, because the text refers that living below the poverty line and speaking a foreign language falls into both categories.
(b) Draw a Venn diagram summarizing the variables and their associated probabilities.
(c) What percent of Americans live below the poverty line and only speak English at home?
14.6% - 4.2% = 10.4%
(d) What percent of Americans live below the poverty line or speak a foreign language at home?
(20.7% + 14.6%) - 4.2% = 31.1%
(e) What percent of Americans live above the poverty line and only speak English at home?
100% - (14.6% + 20.7% - 4.2%) = 68.9%
(f) Is the event that someone lives below the poverty line independent of the event that the person
speaks a foreign language at home?
Is P(Poverty) x P(Foreign Language) = P(Poverty and Foreign Language), 0.146 x 0.207 = 0.042? 0.030 does not equal 0.042. Therefore, the events are not independent of each other.

2.20 Assortative mating. Assortative mating is a nonrandom mating pattern where individuals
with similar genotypes and/or phenotypes mate with one another more frequently than what would
be expected under a random mating pattern. Researchers studying this topic collected data on
eye colors of 204 Scandinavian men and their female partners. The table below summarizes the
results. For simplicity, we only include heterosexual relationships in this exercise.
(a) What is the probability that a randomly chosen male respondent or his partner has blue eyes?
P(Sm Blue or Pf Blue)   = (P(Sm Blue) + P(Pf Blue) - P(Sm Blue and Pf Blue)) / P(Ttl) 
                        = (108 + 114 - 78) / 204
                        = 0.7058 ~ 70.58%
(b) What is the probability that a randomly chosen male respondent with blue eyes has a partner
with blue eyes?
P(Sm Blue and Pf Blue)  = (P(Sm Blue) / P(Ttl)) / (P(Sm Blue Ttl) / P(Ttl))
                        = (78 / 204) / (114 / 204)
                        = 0.6842 ~ 68.42%
(c) What is the probability that a randomly chosen male respondent with brown eyes has a partner
with blue eyes? 
P(Sm Brown and Pf Blue) = (P(Sm Brown) / P(Ttl)) / (P(Sm Brown Ttl) / P(Ttl))
                        = (19 / 204) / (54 / 204)
                        = 0.3518 ~ 35.18%
What about the probability of a randomly chosen male respondent with green eyes having a partner with blue eyes?
P(Sm Green and Pf Blue) = (P(Sm Green) / P(Ttl)) / (P(Sm Green Ttl) / P(Ttl))
                        = (11 / 204) / (36 / 204)
                        = 0.3055 ~ 30.55%
(d) Does it appear that the eye colors of male respondents and their partners are independent?
Explain your reasoning.

2.30 Books on a bookshelf. The table below shows the distribution of books on a bookcase
based on whether they are nonfiction or fiction and hardcover or paperback.
(a) Find the probability of drawing a hardcover book first then a paperback fiction book second
when drawing without replacement.
P(Hardcover then Paperback Fiction) = P(Hardcover) * P(Paperback Fiction)
                                    = (28/95) * (54/94)
                                    = 0.1693 ~ 16.93%
(b) Determine the probability of drawing a fiction book first and then a hardcover book second,
when drawing without replacement.
P(Fiction then Hardcover)           = P(Fiction) * P(Hardcover)
                                    = (72/95) * (28/94)
                                    = 0.2257 ~ 22.57%
(c) Calculate the probability of the scenario in part (b), except this time complete the calculations
under the scenario where the first book is placed back on the bookcase before randomly drawing
the second book.
P(Fiction then Hardcover)           = P(Fiction) * P(Hardcover)
                                    = (72/95) * (28/95)
                                    = 0.2233 ~ 22.33%
(d) The final answers to parts (b) and (c) are very similar. Explain why this is the case.
The denominator of P(Hardcover) changed from 94 to 95 due to replacement. It is too small of a number to make a significant difference.

2.38 Baggage fees. An airline charges the following baggage fees: $25 for the first bag and
$35 for the second. Suppose 54% of passengers have no checked luggage, 34% have one piece of
checked luggage and 12% have two pieces. We suppose a negligible portion of people check more
than two bags.
(a) Build a probability model, compute the average revenue per passenger, and compute the
corresponding standard deviation.
x0 = 0, x1 = $25, x2 = $35
p0 = .54, p1 = .34, p2 = .12
E(X)  = (0 * .54) + ($25 * .34) + ($60 * .12)
      = $15.70
sd(X) = (((0 - 15.70)^2 * .54) + ((25 - 15.70)^2 * .34) + ((60 - 15.70)^2 * .12))^1/2
      = (133.10 + 29.40 + 235.49)^1/2
      = (397.99)^1/2
      = 19.94
(b) About how much revenue should the airline expect for a flight of 120 passengers? With what
standard deviation? Note any assumptions you make and if you think they are justified.
E(120)  = $15.70 * 120
        = $1884
sd(120) = (((0 - 15.70)^2 * .54 * 120) + ((25 - 15.70)^2 * .34 * 120) + ((60 - 15.70)^2 * .12 * 120))^1/2
        = (15972 + 3528 + 28248.8)^1/2
        = $218.53
        
2.44 Income and gender. The relative frequency table below displays the distribution of
annual total personal income (in 2009 inflation-adjusted dollars) for a representative sample of
96,420,486 Americans. These data come from the American Community Survey for 2005-2009.
This sample is comprised of 59% males and 41% females.69
(a) Describe the distribution of total personal income.
The distribution is pretty even with a slight skew to the right. It peaks at salary range from $35k - $49.9k.
(b) What is the probability that a randomly chosen US resident makes less than $50,000 per year?
P(<$50k) = (2.2% + 4.7% + 15.8% + 18.3% + 21.2%)
         = 62.2%
(c) What is the probability that a randomly chosen US resident makes less than $50,000 per year and is female?
Note any assumptions you make.
P(<$50k and female) = 62.2% * 41%
                    = 25.50%
                    *Assuming females are normally distributed between groups
(d) The same data source indicates that 71.8% of females make less than $50,000 per year. Use this value to
determine whether or not the assumption you made in part (c) is valid.
The assumption I made is invalid. 71.8% of females make less than $50k indicates that the data is not normally distributed as assumed in part (c). When taking this information into account, for females, the income for females is in fact left skewed.